In [1]:
# pandas

In [2]:
# pandas is the library used for the data analysis in python 
# it can load the data and also process the data 

# operations like cleaning 
# filling null values 
# switching to appropriate datatype 
# these all are the fetures of pandas
# everything that you can do in excel all thing is done in pandas as well

In [3]:
# pandas store your data in 2 data types 
# 1] series (single column data)
# 2] Dataframe which is the multi column data

In [4]:
# while working with pandas we look into the dataframes
# for creating the dataframe we should have the data 
# that data we can have in multiple formats 
# csv , json , excel , sql

In [6]:
# library means its wrriten by someone else and we are using it in our program for our own usecases 
# pandas is wrriten by Wes McKinney
# performance part of pandas is wrriten in c language 
# with performance-critical parts written in Cython and C

In [8]:
# before importing you should know how to install
!pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# where you will get the data 
# common sources ?
# google form
# kaggle 
# historic resources

In [9]:
import pandas as pd
df = pd.read_csv("data.csv")

In [10]:
df

    Feature  Target
0      -3.0    20.2
1      -2.7    16.9
2      -2.4    14.1
3      -2.1    11.8
4      -1.8     9.3
5      -1.5     8.0
6      -1.2     6.1
7      -0.9     5.7
8      -0.6     4.2
9      -0.3     3.9
10      0.0     3.4
11      0.3     3.8
12      0.6     4.9
13      0.9     6.0
14      1.2     7.8
15      1.5    10.0
16      1.8    13.2
17      2.1    16.9
18      2.4    20.8
19      2.7    25.4

In [14]:
df = pd.read_csv("train.csv")

In [16]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
df.to_excel("titanic_excel.xlsx" , index = False)

In [21]:
import pandas as pd
df = pd.read_excel("titanic_excel.xlsx")

In [22]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
print("hello")

hello